# Шаг 1: Используем официальный Node.js образ для сборки
FROM node:20 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы приложения
COPY . .

# Строим проект
RUN npm run build

# Шаг 2: Используем Nginx для деплоя собранного приложения
FROM nginx:alpine

# Копируем файлы из этапа сборки в Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
